CREATE TABLE `mobile_food` (
   `id` int(11) NOT NULL AUTO_INCREMENT,
   `location_id` bigint(20) NOT NULL,
   `applicant` varchar(100) DEFAULT NULL,
   `facility_type` varchar(10) DEFAULT NULL COMMENT '设施类型： 1-trunk 2-push cart 3-未知',
   `cnn` bigint(20) DEFAULT NULL,
   `location_description` varchar(255) DEFAULT NULL,
   `address` varchar(255) DEFAULT NULL,
   `block_lot` varchar(50) DEFAULT NULL,
   `block` varchar(50) DEFAULT NULL,
   `lot` varchar(50) DEFAULT NULL,
   `permit` varchar(50) DEFAULT NULL,
   `status` varchar(20) DEFAULT NULL,
   `food_items` varchar(1000) DEFAULT NULL,
   `x` bigint(20) DEFAULT NULL,
   `y` bigint(20) DEFAULT NULL,
   `latitude` decimal(10,0) DEFAULT NULL,
   `longitude` decimal(10,0) DEFAULT NULL,
   `schedule` varchar(500) DEFAULT NULL,
   `days_hours` varchar(50) DEFAULT NULL,
   `noi_sent` varchar(255) DEFAULT NULL,
   `approved` varchar(50) DEFAULT NULL,
   `received` varchar(10) DEFAULT NULL,
   `prior_permit` tinyint(1) DEFAULT NULL,
   `expiration_date` varchar(50) DEFAULT NULL,
   `location` varchar(100) DEFAULT NULL,
   `fire_prevention_districts` varchar(4) DEFAULT NULL,
   `police_districts` varchar(4) DEFAULT NULL,
   `supervisor_districts` varchar(4) DEFAULT NULL,
   `zip_codes` varchar(10) DEFAULT NULL,
   `neighborhoods` varchar(4) DEFAULT NULL,
   PRIMARY KEY (`id`),
   UNIQUE KEY `idx_uniq_location_id` (`location_id`)
) ENGINE=InnoDB AUTO_INCREMENT=490 DEFAULT CHARSET=utf8mb4;

